### PR TITLE
Fix byte rcv loss stat

### PR DESCRIPTION
**Pull request by guilletrejo**
Updated submodule srt to fix error on stat file generated by srt-xtransmit (the column Byte Rcv Loss was the same as Byte Rcv Total because of a bug in `srtcore/core.cpp` that was fixed long ago in the main repo).

### CODE REVIEW

**Comment by maxsharabayko** [comment]
Hi. I wonder why did you close the PR?

**Comment by guilletrejo** [comment]
Hi @maxsharabayko , I didn't mean to open it in the first place. It was meant to be opened on a fork to update the srt submodule.

**Comment by maxsharabayko** [comment]
I see. Multicast support looks interesting. If you would consider submitting a PR for it, might be a useful improvement. 🙂

**Comment by guilletrejo** [comment]
@maxsharabayko You can check out this fork https://github.com/swxtchio/srt-xtransmit

**Pull request closed without merging**
